### ISSUE TITLE
[Bug] Hover translations not working

### ISSUE THREAD

**Issue by SrBedrock** [Ghost-chu/QuickShopList#3]
Hover translations not working
![image](https://user-images.githubusercontent.com/51332006/91119830-9c371980-e66a-11ea-8ad5-670eb2cdbaff.png)

Config.yml
```yml
lang:
  desc: "Listar todos as suas lojas."
  prefix: "&6Lista de Lojas &b- &eTotal: {total}"
  coord: "&a{num}. &e{name}"
  nothing: "&c&lAVISO!&r &eVocê não possui nenhuma loja."
  hover:
    - "&e{name}"
    - "&7{world}, {x}, {y}, {z}"
    - "&bPreço &e{name} &b - &6{price} por stack"
    - "&aLoja &b{type} &aitens"
  selling: "VENDENDO"
  buying: "COMPRANDO"
```
